In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/persona-data-set/persona.csv


In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

pd.set_option("display.max_rows", None)
pd.set_option("display.width", 500)

In [3]:
np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.random.randint(0, 10, size=10)

array([0, 6, 7, 1, 9, 3, 5, 0, 8, 8])

In [6]:
np.random.normal(10, 4, (3, 4))

array([[15.41903989,  7.35206493,  1.76793313,  7.79823956],
       [12.67737558, 16.64258569,  9.8109456 , 11.64089405],
       [10.301241  ,  9.09680394,  6.67954494,  8.01165615]])

In [7]:
np.random.normal(60, 3, (3, 3))

array([[67.24207067, 60.16629812, 58.33402645],
       [61.92131105, 59.10166448, 59.90476912],
       [56.42413388, 61.49319191, 60.90138652]])

In [8]:
np.random.normal(65, 5, (3, 3))

array([[64.42997122, 74.64930484, 65.42708863],
       [62.73813816, 71.04412018, 61.38041654],
       [64.59225844, 71.12071788, 63.40795115]])

In [9]:
a = np.random.randint(10, size=10)

In [10]:
a[0]

1

In [11]:
a[0:5]

array([1, 7, 7, 5, 7])

In [12]:
m = np.random.randint(10, size=(3, 5))

In [13]:
m[1, 1]

2

In [14]:
m[2, 2]

5

In [15]:
m[3, 3]

IndexError: index 3 is out of bounds for axis 0 with size 3

Rows has 0,1,2 and that means until 3, is not 3.

In [ ]:
m[2, 4] = 3.6 

In [ ]:
m[:, 0] # tüm satırları ve sıfırıncı sütunu seç

In [ ]:
m[1, :] # birinci satır ve tüm sütunları seç

In [ ]:
m[1, :] # birinci satır ve tüm sütunları seç

In [ ]:
m[0:2, 0:3] # satırlarda 0'dan 2'ye kadar, sütunlarda 0'dan 3'e kadar git

Fancy Index

In [ ]:
v = np.arange(0, 30, 3) # sıfırdan otuza kadar 3'er 3'er artan bir array

In [ ]:
v[1]

In [ ]:
catch = [2, 3, 4]
v[catch]

NumPy'da Koşullu İşlemler (Conditions on NumPy)

In [ ]:
v = np.array([1, 2, 3, 4, 5])

In [ ]:
v[v < 3] 

In [ ]:
v[v != 3]

Matematiksel İşlemler (Mathematical Operations)

In [ ]:
v = np.array([1, 2, 3, 4, 5])

In [ ]:
v * 5 / 10

Solving a System of Two Linear Equations with NumPy

In [ ]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]]) # birinci elemanlar birinci değişkenin katsayılarıdır.
                               # ikinciler ikinci değişkenin katsayıları
b = np.array([12, 10]) # sonuçlar ise bu arrayde
np.linalg.solve(a, b)

Data Analysis with Python: Pandas

In [ ]:
s = pd.Series([10, 77, 12, 4, 5])
type(s)

In [ ]:
df = pd.read_csv("/kaggle/input/persona-data-set/persona.csv")
df.head()

In [ ]:
type(df)

In [ ]:
type(df["SEX"])

In [ ]:
type(df["COUNTRY"])

In [ ]:
type(df["AGE"])

In [ ]:
type(df["PRICE"])

In [ ]:
type(df["SOURCE"])

Pandas'ta Seçim İşlemleri (Selection in Pandas)

In [ ]:
df[0:13] # slice işlemi

In [ ]:
df[0:29] # slice işlemi

In [ ]:
df.drop(0, axis=0).head() # kalıcı değil

In [ ]:
delete_indexes = [1, 3, 5, 7]
df.drop(delete_indexes, axis=0).head(10)
df.head()

Converting a Variable to Index

In [ ]:
df["AGE"].head() 
df.AGE.head() 
# aynı

In [ ]:
df.index = df["AGE"]
df.head()

In [ ]:
df.drop("AGE", axis=1).head()

In [ ]:
df.loc[df["COUNTRY"] == "tur"].head()

In [ ]:
df.loc[df["COUNTRY"] == "tur", ["AGE", "SOURCE"]].head()

In [ ]:
df.iloc[0:3, 0:3]

In [ ]:
df.iloc[[1, 3, 5], [0, 1]]

In [ ]:
df.iloc[3:6, 1:3]

Koşullu Seçim (Conditional Selection)

In [ ]:
df.loc[(df["AGE"] > 20) | (df["SEX"] == "male") & (df["SOURCE"] == "android"), ["PRICE", "COUNTRY"]].head() 

Toplulaştırma & Gruplama (Aggregation & Grouping)

In [ ]:
df.groupby("SEX").agg({"AGE" : "mean", "PRICE" : ["mean", "sum"]})

Pivot Table

In [ ]:
df.pivot_table(values="PRICE", index="COUNTRY", columns="SOURCE", aggfunc="sum")

Apply & Lambda

In [ ]:
df = df.reset_index(drop=True)
df.head()

In [ ]:
df.loc[:, df.columns.str.contains("AGE")].apply(lambda x: x*2).head()

In [ ]:
df.index = df["SEX"]
df.head()

In [ ]:
df.index = df["COUNTRY"]
df.head()

In [ ]:
df.index = df["SOURCE"]
df.head()

In [ ]:
df.index = df["PRICE"]
df.head()