In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/persona-data-set/persona.csv


In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

pd.set_option("display.max_rows", None)
pd.set_option("display.width", 500)

In [3]:
np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.random.randint(0, 10, size=10)

array([4, 4, 0, 8, 3, 6, 0, 3, 6, 8])

In [6]:
np.random.normal(10, 4, (3, 4))

array([[-0.54592985,  9.32133634,  8.70056517, 12.94211288],
       [12.43527704,  7.75491207,  5.0775824 ,  6.92417285],
       [ 8.10763283,  8.71382476,  5.39726341,  7.85347163]])

In [7]:
np.random.normal(60, 3, (3, 3))

array([[54.74410551, 63.85054983, 61.03941433],
       [60.10676459, 57.92308571, 59.48853157],
       [56.49299134, 65.5608656 , 60.91372675]])

In [8]:
np.random.normal(65, 5, (3, 3))

array([[56.95524544, 69.35187584, 68.43019977],
       [65.34259178, 65.38175245, 62.51104097],
       [62.3304003 , 67.57730175, 69.85993604]])

In [9]:
a = np.random.randint(10, size=10)

In [10]:
a[0]

2

In [11]:
a[0:5]

array([2, 6, 4, 7, 4])

In [12]:
m = np.random.randint(10, size=(3, 5))

In [13]:
m[1, 1]

5

In [14]:
m[2, 2]

4

In [15]:
m[2, 4] = 3.6 

In [16]:
m[:, 0] # tüm satırları ve sıfırıncı sütunu seç

array([4, 2, 9])

In [17]:
m[1, :] # birinci satır ve tüm sütunları seç

array([2, 5, 8, 9, 6])

In [18]:
m[1, :] # birinci satır ve tüm sütunları seç

array([2, 5, 8, 9, 6])

In [19]:
m[0:2, 0:3] # satırlarda 0'dan 2'ye kadar, sütunlarda 0'dan 3'e kadar git

array([[4, 3, 7],
       [2, 5, 8]])

Fancy Index

In [20]:
v = np.arange(0, 30, 3) # sıfırdan otuza kadar 3'er 3'er artan bir array

In [21]:
v[1]

3

In [22]:
catch = [2, 3, 4]
v[catch]

array([ 6,  9, 12])

NumPy'da Koşullu İşlemler (Conditions on NumPy)

In [23]:
v = np.array([1, 2, 3, 4, 5])

In [24]:
v[v < 3] 

array([1, 2])

In [25]:
v[v != 3]

array([1, 2, 4, 5])

Matematiksel İşlemler (Mathematical Operations)

In [26]:
v = np.array([1, 2, 3, 4, 5])

In [27]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

Solving a System of Two Linear Equations with NumPy

In [28]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]]) # birinci elemanlar birinci değişkenin katsayılarıdır.
                               # ikinciler ikinci değişkenin katsayıları
b = np.array([12, 10]) # sonuçlar ise bu arrayde
np.linalg.solve(a, b)

array([1.85714286, 2.71428571])

Data Analysis with Python: Pandas

In [29]:
s = pd.Series([10, 77, 12, 4, 5])
type(s)

pandas.core.series.Series

In [30]:
df = pd.read_csv("/kaggle/input/persona-data-set/persona.csv")
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17

In [31]:
type(df)

pandas.core.frame.DataFrame

In [32]:
type(df["SEX"])

pandas.core.series.Series

In [33]:
type(df["COUNTRY"])

pandas.core.series.Series

In [34]:
type(df["AGE"])

pandas.core.series.Series

In [35]:
type(df["PRICE"])

pandas.core.series.Series

In [36]:
type(df["SOURCE"])

pandas.core.series.Series

Pandas'ta Seçim İşlemleri (Selection in Pandas)

In [37]:
df[0:13] # slice işlemi

PRICE   SOURCE   SEX COUNTRY  AGE
0      39  android  male     bra   17
1      39  android  male     bra   17
2      49  android  male     bra   17
3      29  android  male     tur   17
4      49  android  male     tur   17
5      29  android  male     bra   17
6      19  android  male     bra   17
7      59  android  male     bra   17
8      49  android  male     bra   17
9      19  android  male     bra   17
10     49  android  male     bra   17
11     39  android  male     bra   17
12     19  android  male     bra   17

In [38]:
df[0:29] # slice işlemi

PRICE   SOURCE     SEX COUNTRY  AGE
0      39  android    male     bra   17
1      39  android    male     bra   17
2      49  android    male     bra   17
3      29  android    male     tur   17
4      49  android    male     tur   17
5      29  android    male     bra   17
6      19  android    male     bra   17
7      59  android    male     bra   17
8      49  android    male     bra   17
9      19  android    male     bra   17
10     49  android    male     bra   17
11     39  android    male     bra   17
12     19  android    male     bra   17
13     49  android    male     bra   17
14     39  android    male     bra   17
15     49  android    male     bra   17
16     29  android    male     bra   17
17     29  android  female     usa   26
18      9  android  female     usa   26
19     49      ios  female     bra   26
20     19      ios  female     bra   26
21     29      ios  female     bra   26
22     49      ios  female     bra   26
23     49      ios  female     bra   26
24     19  android  female     usa   23
25     19  android  female     usa   23
26     39  android  female     usa   23
27     29  android  female     usa   23
28     19  android  female     usa   23

In [39]:
df.drop(0, axis=0).head() # kalıcı değil

PRICE   SOURCE   SEX COUNTRY  AGE
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17
5     29  android  male     bra   17

In [40]:
delete_indexes = [1, 3, 5, 7]
df.drop(delete_indexes, axis=0).head(10)
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17

Converting a Variable to Index

In [41]:
df["AGE"].head() 
df.AGE.head() 
# aynı

0    17
1    17
2    17
3    17
4    17
Name: AGE, dtype: int64

In [42]:
df.index = df["AGE"]
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
AGE                                   
17      39  android  male     bra   17
17      39  android  male     bra   17
17      49  android  male     bra   17
17      29  android  male     tur   17
17      49  android  male     tur   17

In [43]:
df.drop("AGE", axis=1).head()

PRICE   SOURCE   SEX COUNTRY
AGE                              
17      39  android  male     bra
17      39  android  male     bra
17      49  android  male     bra
17      29  android  male     tur
17      49  android  male     tur

In [44]:
df.loc[df["COUNTRY"] == "tur"].head()

PRICE   SOURCE   SEX COUNTRY  AGE
AGE                                   
17      29  android  male     tur   17
17      49  android  male     tur   17
42      19      ios  male     tur   42
42      39      ios  male     tur   42
42      39      ios  male     tur   42

In [45]:
df.loc[df["COUNTRY"] == "tur", ["AGE", "SOURCE"]].head()

AGE   SOURCE
AGE              
17    17  android
17    17  android
42    42      ios
42    42      ios
42    42      ios

In [46]:
df.iloc[0:3, 0:3]

PRICE   SOURCE   SEX
AGE                      
17      39  android  male
17      39  android  male
17      49  android  male

In [47]:
df.iloc[[1, 3, 5], [0, 1]]

PRICE   SOURCE
AGE                
17      39  android
17      29  android
17      29  android

In [48]:
df.iloc[3:6, 1:3]

SOURCE   SEX
AGE               
17   android  male
17   android  male
17   android  male

Koşullu Seçim (Conditional Selection)

In [49]:
df.loc[(df["AGE"] > 20) | (df["SEX"] == "male") & (df["SOURCE"] == "android"), ["PRICE", "COUNTRY"]].head() 

PRICE COUNTRY
AGE               
17      39     bra
17      39     bra
17      49     bra
17      29     tur
17      49     tur

Toplulaştırma & Gruplama (Aggregation & Grouping)

In [50]:
df.groupby("SEX").agg({"AGE" : "mean", "PRICE" : ["mean", "sum"]})

AGE      PRICE       
             mean       mean    sum
SEX                                
female  23.508966  33.952308  88989
male    23.661202  34.329971  81671

Pivot Table

In [51]:
df.pivot_table(values="PRICE", index="COUNTRY", columns="SOURCE", aggfunc="sum")

SOURCE   android    ios
COUNTRY                
bra        32874  18480
can         4233   3497
deu         9111   6374
fra         5490   4687
tur         8369   7320
usa        41559  28666

Apply & Lambda

In [52]:
df = df.reset_index(drop=True)
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17

In [53]:
df.loc[:, df.columns.str.contains("AGE")].apply(lambda x: x*2).head()

AGE
0   34
1   34
2   34
3   34
4   34

In [54]:
df.index = df["SEX"]
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
SEX                                    
male     39  android  male     bra   17
male     39  android  male     bra   17
male     49  android  male     bra   17
male     29  android  male     tur   17
male     49  android  male     tur   17

In [55]:
df.index = df["COUNTRY"]
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
COUNTRY                                   
bra         39  android  male     bra   17
bra         39  android  male     bra   17
bra         49  android  male     bra   17
tur         29  android  male     tur   17
tur         49  android  male     tur   17

In [56]:
df.index = df["SOURCE"]
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
SOURCE                                    
android     39  android  male     bra   17
android     39  android  male     bra   17
android     49  android  male     bra   17
android     29  android  male     tur   17
android     49  android  male     tur   17

In [57]:
df.index = df["PRICE"]
df.head()

PRICE   SOURCE   SEX COUNTRY  AGE
PRICE                                   
39        39  android  male     bra   17
39        39  android  male     bra   17
49        49  android  male     bra   17
29        29  android  male     tur   17
49        49  android  male     tur   17